# Generated by Django 5.1.4 on 2024-12-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employ',
            name='job_title',
            field=models.CharField(max_length=150, null=type),
            preserve_default=type,
        ),
        migrations.AddField(
            model_name='employ',
            name='status',
            field=models.IntegerField(choices=[(1, 'working'), (2, 'not working')], default=1),
        ),
    ]
